import { useEffect, useState } from 'react';
import './company.css';
const API = 'http://127.0.0.1:8000';
const labelKeys = ['topic', 'sentiment', 'urgency', 'intent', 'emotion'];

function Nav({ active, setPage, user, logout }) { const signOut = logout || (() => { localStorage.removeItem('company_session'); window.location.reload(); }); return <aside><div className="console-logo"><span className="console-mark">N</span><b>Nexora Console<small>Customer Response Center</small></b></div><button className={active === 'inbox' ? 'active' : ''} onClick={() => setPage('inbox')}>Inbox</button>{user.role === 'admin' ? <><button className={active === 'escalations' ? 'active' : ''} onClick={() => setPage('escalations')}>Escalations</button><button className={active === 'analytics' ? 'active' : ''} onClick={() => setPage('analytics')}>Analytics</button></> : <button className={active === 'team' ? 'active' : ''} onClick={() => setPage('team')}>Team inbox</button>}<div className="company-profile"><b>{user.name}</b><small>{user.role === 'admin' ? 'Administrator' : user.team}</small></div><button onClick={signOut}>Sign out</button></aside>; }
const Status = ({ value }) => <span className="pill">{String(value || 'pending').replace('_', ' ')}</span>;

export default function CompanyPortal() {
  const savedSession = localStorage.getItem('company_session');
  const [form, setForm] = useState({ email: '', password: '' }), [token, setToken] = useState(() => savedSession ? JSON.parse(savedSession).token : ''), [user, setUser] = useState(() => savedSession ? JSON.parse(savedSession).user : null), [page, setPage] = useState('inbox'), [complaints, setComplaints] = useState([]), [detail, setDetail] = useState(null), [reply, setReply] = useState(''), [escalations, setEscalations] = useState([]), [teamItems, setTeamItems] = useState([]), [selectedTeamItem, setSelectedTeamItem] = useState(null), [analytics, setAnalytics] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [saving, setSaving] = useState(false);
  const api = async (path, options = {}) => { const r = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); const d = await r.json(); if (!r.ok) throw Error(d.detail || 'Request failed'); return d; };
  const loadPage = async (target = page) => { setError(''); try { if (target === 'inbox') setComplaints((await api('/company/complaints')).complaints); if (target === 'escalations') setEscalations((await api('/company/escalations')).escalations); if (target === 'team') setTeamItems((await api('/company/team/inbox')).items); if (target === 'analytics') setAnalytics(await api('/company/analytics')); } catch (err) { setError(err.message); } };
  useEffect(() => { if (token) loadPage(page); }, [token, page]);
  const login = async (e) => { e.preventDefault(); try { const d = await api('/auth/company/login', { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('company_session', JSON.stringify({ token: d.token, user: d.user })); setToken(d.token); setUser(d.user); setPage(d.user.role === 'admin' ? 'inbox' : 'team'); } catch (err) { setError(err.message); } };
  const logout = () => { localStorage.removeItem('company_session'); setToken(''); setUser(null); };
  const open = async (id) => { try { const d = await api(`/company/complaints/${id}`); setDetail(d); setReply(d.llm_response || ''); setPage('detail'); } catch (err) { setError(err.message); } };
  const save = async (action) => { if (!reply.trim()) return; setSaving(true); try { const d = await api(`/company/complaints/${detail.id}/response`, { method: 'PATCH', body: JSON.stringify({ response_text: reply, action }) }); setNotice(d.message); if (action === 'approved') setPage('inbox'); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const sendHumanReply = async (id, response) => { if (!response.trim()) return; setSaving(true); try { setNotice((await api(`/company/escalations/${id}/reply`, { method: 'POST', body: JSON.stringify({ response_text: response }) })).message); setSelectedTeamItem(null); await loadPage('team'); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const changePage = (next) => { setSelectedTeamItem(null); setPage(next); };
  if (!user) return <main className="company-login"><section><div className="company-login-card"><span className="console-mark">N</span><p className="portal-label">NEXORA COMPANY PORTAL</p><h1>Command center</h1><p>Manage safe, consistent customer responses.</p><form onSubmit={login}><input placeholder="Work email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /><input placeholder="Password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /><button className="company-primary">Log in</button></form><p className="demo-box">Admin: admin@npn.demo<br />Team: support@npn.demo<br />Password: password123</p>{error && <p className="company-error">{error}</p>}</div></section></main>;
  if (page === 'detail') return <main className="company-app"><Nav active="inbox" setPage={changePage} user={user} /><section className="company-content"><button className="back-link dark" onClick={() => setPage('inbox')}>Back to inbox</button><div className="heading"><div><p className="portal-label">RESPONSE REVIEW</p><h1>{detail.user?.name}</h1><p>{detail.user?.email}</p></div><Status value={detail.response_status} /></div><article className="message-card"><p className="portal-label">CUSTOMER MESSAGE</p><p>{detail.text}</p></article>{detail.conversation_history?.length > 1 && <section className="message-card"><p className="portal-label">CUSTOMER MEMORY</p>{detail.conversation_history.slice(0, -1).map((item) => <div key={item.id}><b>Customer</b><p>{item.text}</p>{item.response && <><b>Nexora</b><p>{item.response}</p></>}</div>)}</section>}{detail.escalation ? <section className="escalation-callout"><b>Escalated to {detail.escalation.team}</b><p>{detail.escalation.priority} · {detail.escalation.reason}</p>{detail.human_response ? <p>{detail.human_response}</p> : <small>Awaiting a human reply from the assigned team.</small>}</section> : <><div className="labels">{labelKeys.map((key) => <span key={key}><small>{key}</small><b>{detail.labels?.[key] || '—'}</b></span>)}</div><section className="reply"><p className="portal-label">AI DRAFT — REVIEW BEFORE SENDING</p><textarea value={reply} onChange={(e) => setReply(e.target.value)} /><div><button disabled={saving} onClick={() => save('draft')}>Save draft</button><button className="company-primary" disabled={saving} onClick={() => save('approved')}>Approve & reply</button></div></section></>}{error && <p className="company-error">{error}</p>}{notice && <p className="company-notice">{notice}</p>}</section></main>;
  return <main className="company-app"><Nav active={page} setPage={changePage} user={user} /><section className="company-content"><div className="heading"><div><p className="portal-label">{page === 'team' ? user.team : 'NEXORA OPERATIONS'}</p><h1>{page === 'inbox' ? 'Customer inbox' : page === 'team' ? 'Team inbox' : page === 'escalations' ? 'Escalation oversight' : 'Performance analytics'}</h1><p>{page === 'team' ? 'Only work routed to your team is shown here. Select a message to write a human response.' : 'Review work that needs your attention.'}</p></div><button className="refresh" onClick={() => loadPage(page)}>Refresh</button></div>{error && <p className="company-error">{error}</p>}{notice && <p className="company-notice">{notice}</p>}{page === 'inbox' && <Inbox items={complaints} open={open} />}{page === 'escalations' && <Escalations items={escalations} />}{page === 'team' && <TeamInbox items={teamItems} selected={selectedTeamItem} select={setSelectedTeamItem} send={sendHumanReply} saving={saving} />}{page === 'analytics' && <Analytics data={analytics} />}</section></main>;
}
function Inbox({ items, open }) { return <div className="list">{items.length ? items.map((item) => <button key={item.id} onClick={() => open(item.id)}><i className={item.labels?.urgency} /><div><b>{item.user_name}</b><p>{item.text}</p><small>{item.labels?.topic} · {item.labels?.sentiment} · <Status value={item.response_status} /></small></div></button>) : <p className="empty">No customer messages yet.</p>}</div>; }
function Escalations({ items }) { return <div className="cards">{items.length ? items.map((item) => <article key={item.id}><span className={`priority ${item.priority}`}>{item.priority}</span><h3>{item.team}</h3><p>{item.text}</p><small>{item.reason}</small><Status value={item.status} />{item.human_response && <div className="team-reply"><b>Team response</b><p>{item.human_response}</p></div>}</article>) : <p className="empty">No escalations found.</p>}</div>; }
function TeamInbox({ items, selected, select, send, saving }) { const [text, setText] = useState(''); useEffect(() => setText(''), [selected?.id]); return <div className="team-inbox"><div className="list">{items.length ? items.map((item) => <button key={item.id} onClick={() => select(item)}><i className={item.priority === 'P1' ? 'high' : 'medium'} /><div><b>{item.customer}</b><p>{item.text}</p><small>{item.reason} · <span className={`priority ${item.priority}`}>{item.priority}</span></small></div></button>) : <p className="empty">Your team has no open escalations.</p>}</div>{selected && <section className="reply"><p className="portal-label">HUMAN RESPONSE</p><h2>{selected.customer}</h2><p>{selected.text}</p><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Write the team response…" /><div><button className="company-primary" disabled={saving || !text.trim()} onClick={() => send(selected.id, text)}>{saving ? 'Sending…' : 'Send response'}</button></div></section>}</div>; }
function Analytics({ data }) { if (!data) return <p className="empty">Loading analytics…</p>; const groups = [['Sentiment', data.sentiment], ['Topics', data.topics], ['Urgency', data.urgency]]; const points = data.daily_volume || []; const max = Math.max(...points.map((p) => p.count), 1); const line = points.map((p, i) => `${20 + i * (300 / Math.max(points.length - 1, 1))},${125 - (p.count / max) * 95}`).join(' '); return <><div className="stats"><article><small>Total mentions</small><b>{data.total_mentions}</b></article><article><small>Open escalations</small><b>{data.open_escalations}</b></article><article><small>Approved responses</small><b>{data.approved_responses}</b></article></div><div className="breakdowns"><section><h3>Incoming volume</h3><svg viewBox="0 0 340 150" style={{ width: '100%', display: 'block' }} role="img" aria-label="Daily incoming mentions"><path d="M20 125H320 M20 78H320 M20 30H320" stroke="#dce5ed" fill="none" /><polyline points={line} fill="none" stroke="#1c9b71" strokeWidth="4" />{points.map((p, i) => <circle key={p.date} cx={20 + i * (300 / Math.max(points.length - 1, 1))} cy={125 - (p.count / max) * 95} r="4" fill="#1c9b71"><title>{`${p.date}: ${p.count} mentions`}</title></circle>)}</svg><small>Last {points.length} active days</small></section><section><h3>Topic routing</h3>{Object.entries(data.topics || {}).map(([key, value]) => <p key={key}><span>{key.replace('_', ' ')}</span><b>{value}</b></p>)}</section><section><h3>Response health</h3><p><span>Approved</span><b>{data.approved_responses}</b></p><p><span>Escalated</span><b>{data.open_escalations}</b></p></section></div><div className="breakdowns">{groups.map(([title, values]) => <section key={title}><h3>{title}</h3>{Object.entries(values || {}).map(([key, value]) => <p key={key}><span>{key.replace('_', ' ')}</span><b>{value}</b></p>)}</section>)}</div></>; }
