import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './social.css';
import CompanyPortal from './company.jsx';
const API = 'http://127.0.0.1:8000';
const trends = ['#Nexora', '#CustomerCare', 'Service update'];
function Avatar({ user, small = false }) { return <span className={`avatar ${small ? 'small-avatar' : ''} ${user?.color || 'green'}`}>{user?.name?.[0] || 'N'}</span>; }
function ThreadTweet({ post, replies, onReply, depth = 0 }) { const status = post.processing_status; return <article className={`tweet ${depth ? 'tweet-reply' : ''}`}><Avatar user={post.author} /><div className="tweet-body"><div><b>{post.author.name}</b> <small>{post.author.handle} · just now</small></div><p>{post.text}</p>{status === 'processing' && <em className="processing">Nexora is reviewing this mention…</em>}{status === 'escalated' && <em>Escalated to a Nexora specialist</em>}{post.companyReply && <div className="company-reply"><Avatar user={{ name: 'Nexora', color: 'blue' }} small /><div><b>Nexora</b> <small>@nexora · Reply</small><p>{post.companyReply.text}</p><button className="reply-link" onClick={() => onReply(post, true)}>Reply to Nexora</button></div></div>}<div className="actions"><button onClick={() => onReply(post, false)}>Reply</button><span>Repost</span><span>Like</span></div>{(replies[post.id] || []).map((child) => <ThreadTweet key={child.id} post={child} replies={replies} onReply={onReply} depth={depth + 1} />)}</div></article>; }
function TwitterApp() {
  const savedUser = localStorage.getItem('twitter_user');
  const [user, setUser] = useState(() => savedUser ? JSON.parse(savedUser) : null), [identifier, setIdentifier] = useState(''), [password, setPassword] = useState(''), [text, setText] = useState(''), [posts, setPosts] = useState([]), [error, setError] = useState(''), [posting, setPosting] = useState(false), [notice, setNotice] = useState(''), [replyingTo, setReplyingTo] = useState(null);
  const loadTweets = async () => { try { const r = await fetch(`${API}/social/tweets`); const d = await r.json(); if (r.ok) setPosts(d.tweets.map((tweet) => ({ ...tweet, companyReply: tweet.company_reply }))); } catch { setError('Could not refresh the timeline. Is the API running?'); } };
  useEffect(() => { if (!user) return; loadTweets(); const timer = setInterval(loadTweets, 2000); return () => clearInterval(timer); }, [user]);
  const login = async (e) => { e.preventDefault(); setError(''); try { const r = await fetch(`${API}/auth/social/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ identifier, password }) }); const d = await r.json(); if (!r.ok) throw Error(d.detail); localStorage.setItem('twitter_user', JSON.stringify(d.user)); setUser(d.user); } catch (err) { setError(err.message); } };
  const logout = () => { localStorage.removeItem('twitter_user'); setUser(null); setPosts([]); };
  const cancelReply = () => { setReplyingTo(null); setText(''); };
  const startReply = (tweet, isBrandReply) => { setReplyingTo(tweet); if (isBrandReply && !text.trim()) setText('@nexora '); document.querySelector('textarea')?.focus(); };
  const post = async (e) => { e.preventDefault(); const message = text.trim(); if (!message || posting) return; setPosting(true); setText(''); const optimistic = { id: `local-${Date.now()}`, author: user, text: message, processing_status: replyingTo?.companyReply || message.toLowerCase().includes('@nexora') ? 'processing' : null, parent_tweet_id: replyingTo?.id || null }; setPosts((current) => [optimistic, ...current]); try { const r = await fetch(`${API}/social/tweets`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: user.name, email: user.email, handle: user.handle, platform: 'Twitter', text: message, parent_tweet_id: replyingTo?.id || null }) }); const d = await r.json(); if (!r.ok) throw Error(d.detail); setNotice(d.message); setReplyingTo(null); await loadTweets(); } catch (err) { setPosts((current) => current.filter((item) => item.id !== optimistic.id)); setText(message); setError(err.message); } finally { setPosting(false); } };
  if (!user) return <main className="login-page"><form className="login-card" onSubmit={login}><span className="brand-mark big">T</span><p className="social-kicker">NEXORA TWITTER DEMO</p><h1>Sign in to Twitter</h1><input placeholder="Username or email" value={identifier} onChange={(e) => setIdentifier(e.target.value)} required /><input placeholder="Password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /><button>Log in</button>{error && <p className="error-text">{error}</p>}<p className="demo-box">Demo accounts · password: <b>password123</b><br />@nikhil · @nandha · @neha · @arjun</p></form></main>;
  const replies = posts.reduce((all, item) => { if (item.parent_tweet_id) (all[item.parent_tweet_id] ||= []).push(item); return all; }, {}); const roots = posts.filter((item) => !item.parent_tweet_id);
  return <main className="social-app"><aside className="left-rail"><div className="logo"><span className="brand-mark">T</span> Twitter</div><button className="nav active">Home</button><button className="nav">Explore</button><button className="nav">Notifications</button><button className="nav">Messages</button><button className="post-button" onClick={() => { cancelReply(); document.querySelector('textarea')?.focus(); }}>Post</button><button className="profile-button" onClick={logout}><Avatar user={user} /><span><b>{user.name}</b><small>{user.handle}</small></span><b>Sign out</b></button></aside><section className="feed"><header><b>Home</b><small>For you</small></header><form className="composer" onSubmit={post}><Avatar user={user} /><div>{replyingTo && <div className="replying-banner">Replying to {replyingTo.companyReply ? '@nexora' : replyingTo.author.handle}<button type="button" onClick={cancelReply}>Cancel reply</button></div>}<textarea value={text} maxLength="5000" onChange={(e) => setText(e.target.value)} placeholder={replyingTo ? 'Post your reply' : "What's happening?"} /><div className="composer-bar"><span>Media · GIF · Emoji</span><small>{text.length}/5000</small><button disabled={posting || !text.trim()}>{posting ? 'Posting…' : 'Post'}</button></div></div></form>{notice && <p className="notice">{notice}</p>}{error && <p className="notice error-note">{error}</p>}{roots.map((item) => <ThreadTweet post={item} key={item.id} replies={replies} onReply={startReply} />)}</section><aside className="right-rail"><div className="search"><input placeholder="Search Twitter" /></div><section className="side-card"><h2>What’s happening</h2>{trends.map((trend, index) => <p key={trend}><small>Trending in India</small><b>{trend}</b><small>{(12 + index * 9)}K posts</small></p>)}</section></aside></main>;
}
function App() { if (window.location.pathname === '/company') return <CompanyPortal />; if (window.location.pathname !== '/twitter') window.history.replaceState({}, '', '/twitter'); return <TwitterApp />; }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
